<a href="https://colab.research.google.com/github/muyangren907/Machine_Learning/blob/master/TensorFlow%E5%AD%A6%E4%B9%A0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 第一个TensorFlow程序（Hello World）

In [3]:
import tensorflow as tf
message = tf.constant("Hello World")
with tf.Session() as sess:
  print(sess.run(message).decode())

Hello World


# TensorFlow程序结构

In [6]:
v_1 = tf.constant([1,2,3,4])
v_2 = tf.constant([2,1,5,3])
v_add = tf.add(v_1,v_2) # You can also write v_1 + v_2

with tf.Session() as sess:
  print(sess.run(v_add))

# You can also write
# sess = tf.Session()
# print(sess.run(v_add))
# sess.close()

[3 3 8 7]


如果你正在使用 Jupyter Notebook 或者 Python shell 进行编程，使用 tf.InteractiveSession 将比 tf.Session 更方便。InteractiveSession 使自己成为默认会话，因此你可以使用 eval() 直接调用运行张量对象而不用显式调用会话。下面给出一个例子：

In [8]:
sess = tf.InteractiveSession()
v_1 = tf.constant([1,2,3,4])
v_2 = tf.constant([2,1,5,3])
v_add = tf.add(v_1,v_2)
print(v_add.eval())
sess.close()

[3 3 8 7]


/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py:1750: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


# TensorFlow常量、变量和占位符

## TensorFlow 常量

In [36]:
# 声明一个标量常量：
t_1 = tf.constant(4)
with tf.Session() as sess:
  print(sess.run(t_1))

# 一个形如 [1，3] 的常量向量可以用如下代码声明：
t_2 = tf.constant([4,3,2])
with tf.Session() as sess:
  print('\n',sess.run(t_2))

# 要创建一个所有元素为零的张量，可以使用 tf.zeros() 函数。这个语句可以创建
# 一个形如 [M，N] 的零元素矩阵，数据类型（dtype）可以是 int32、float32 等：
# tf.zeros([M,N],tf.dtype)
zero_t = tf.zeros([4,3],tf.int32)
with tf.Session() as sess:
  print('\n',sess.run(zero_t))

# 还可以创建与现有 Numpy 数组或张量常量具有相同形状的张量常量，如下所示：
ones_t = tf.ones_like(zero_t)
with tf.Session() as sess:
  print('\n',sess.run(ones_t))

# 在一定范围内生成一个从初值到终值等差排布的序列：
# tf.linspace(start,stop,num)
# start stop :  fliat
range_t = tf.linspace(1.0,10.0,10)
with tf.Session() as sess:
  print('\n',sess.run(range_t))

# 从开始（默认值=0）生成一个数字序列，增量为 delta（默认值=1），
# 直到终值（但不包括终值）：
# tf.range(start,limit,delta)
range_t = tf.range(1.0,90.0,10)
with tf.Session() as sess:
  print('\n',sess.run(range_t))

# 使用以下语句创建一个具有一定均值（默认值=0.0）和标准差（默认值=1.0）、
# 形状为 [M，N] 的正态分布随机数组：
t_random = tf.random_normal([2,3],2.0,stddev=4,seed=12)
with tf.Session() as sess:
  print('\n',sess.run(t_random))

# 创建一个具有一定均值（默认值=0.0）和标准差（默认值=1.0）、形状为 [M，N] 的
# 截尾正态分布随机数组：
t_random = tf.truncated_normal([1,5],stddev=2,seed=12)
with tf.Session() as sess:
  print('\n',sess.run(t_random))

# 要在种子的 [minval（default=0），maxval] 范围内创建形状为 [M，N] 的给定
# 伽马分布随机数组，请执行如下语句
t_random2 = tf.random_uniform([5,6],maxval=4,seed=12)
with tf.Session() as sess:
  print('\n',sess.run(t_random2))

# 要将给定的张量随机裁剪为指定的大小，使用以下语句：
# t_random 是一个已经定义好的张量。这将导致随机从张量 t_random 中裁剪出一个
# 大小为 [2，5] 的张量。
tf_random_crop = tf.random_crop(t_random2,[4,3],seed=12)
with tf.Session() as sess:
  print('\n',sess.run(tf_random_crop))

# 很多时候需要以随机的顺序来呈现训练样本，可以使用 tf.random_shuffle() 来沿着
# 它的第一维随机排列张量。如果 t_random 是想要重新排序的张量，使用下面的代码：

t_random_shuffle = tf.random_shuffle(tf_random_crop)
with tf.Session() as sess:
  print('\n',sess.run(t_random_shuffle))

# 随机生成的张量受初始种子值的影响。要在多次运行或会话中获得相同的随机数，应该
# 将种子设置为一个常数值。当使用大量的随机张量时，可以使用 tf.set_random_seed() 
# 来为所有随机产生的张量设置种子。以下命令将所有会话的随机张量的种子设置为 54：
tf.set_random_seed(54)

4

 [4 3 2]

 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]

 [[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]

 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

 [ 1. 11. 21. 31. 41. 51. 61. 71. 81.]

 [[-5.3299294  6.88009    6.4126735]
 [ 8.594671  -6.604518  10.532751 ]]

 [[-3.6649647  2.440045   2.2063367  3.2973356  0.3111803]]

 [[0.35454178 3.3739414  0.5591998  0.37541723 0.04065514 3.497334  ]
 [1.4685888  2.7888331  1.9283228  0.3767681  2.2410283  2.9267573 ]
 [1.4547715  2.1593485  1.6037321  3.50946    2.061996   1.9372883 ]
 [0.7182331  1.9995828  3.5743747  3.2437034  0.2526312  0.8461442 ]
 [0.4002676  3.8541117  0.3089533  0.34722805 1.4419994  2.4083471 ]]

 [[3.3739414  0.5591998  0.37541723]
 [2.7888331  1.9283228  0.3767681 ]
 [2.1593485  1.6037321  3.50946   ]
 [1.9995828  3.5743747  3.2437034 ]]

 [[2.7888331  1.9283228  0.3767681 ]
 [1.9995828  3.5743747  3.2437034 ]
 [2.1593485  1.6037321  3.50946   ]
 [3.3739414  0.5591998  0.37541723]]


## TensorFlow 变量

In [0]:
# 它们通过使用变量类来创建。变量的定义还包括应该初始化的常量/随机值。
# 下面的代码中创建了两个不同的张量变量 t_a 和 t_b。
# 两者将被初始化为形状为 [20，30] 的随机均匀分布，最小值=0，最大值=10：
rand_t = tf.random_uniform([20,30],0,10,seed=0)
t_a = tf.Variable(rand_t)
t_b = tf.Variable(rand_t)
# 注意：变量通常在神经网络中表示权重和偏置。

# 下面的代码中定义了两个变量的权重和偏置。
# 权重变量使用正态分布随机初始化，均值为 0，标准差为 2，
# 权重大小为 100×100。偏置由 100 个元素组成，每个元素初始化为 0。
# 在这里也使用了可选参数名以给计算图中定义的变量命名：
weights = tf.Variable(tf.random_normal([100,100],stddev=2))
bias = tf.Variable(tf.zeros(100),name='biases')

# 在前面的例子中，都是利用一些常量来初始化变量，也可以指定一个变量来初始化另一个变量。
# 下面的语句将利用前面定义的权重来初始化 weight2：
weights2 = tf.Variable(weights.initialized_value(),name='w2')

# 变量的定义将指定变量如何被初始化，但是必须显式初始化所有的声明变量。
# 在计算图的定义中通过声明初始化操作对象来实现：
initial_op = tf.global_variables_initializer()

# 每个变量也可以在运行图中单独使用 tf.Variable.initializer 来初始化：
bias = tf.Variable(tf.zeros([100,100]))
with tf.Session() as sess:
  sess.run(bias.initializer)

# 保存变量：使用 Saver 类来保存变量，定义一个 Saver 操作对象：
saver = tf.train.Saver() 

## TensorFlow 占位符

In [46]:
# 介绍完常量和变量之后，我们来讲解最重要的元素——占位符，
# 它们用于将数据提供给计算图。可以使用以下方法定义一个占位符：
# tf.placeholder(dtype,shape=None,name=None)
# dtype 定占位符的数据类型，并且必须在声明占位符时指定。
# 在这里，为 x 定义一个占位符并计算 y=2*x，使用 feed_dict 输入一个随机的 4×5 矩阵：
x = tf.placeholder(tf.float32)
y = 2 * x
data = tf.random_uniform([4,5],10)
with tf.Session() as sess:
  x_data = sess.run(data)
  y_ = sess.run(y,feed_dict={x:x_data})
print(x_data)
print(y_)

[[3.1778164 8.709591  7.535771  5.544607  4.6875687]
 [6.2226806 5.981759  7.0217867 4.8371143 5.2493024]
 [3.974957  3.2180357 5.5360594 7.096443  1.7906361]
 [6.8016834 4.996413  8.032926  5.7051115 3.8984604]]
[[ 6.355633  17.419182  15.071542  11.089214   9.375137 ]
 [12.445361  11.963518  14.043573   9.674229  10.498605 ]
 [ 7.949914   6.4360714 11.072119  14.192886   3.5812721]
 [13.603367   9.992826  16.065851  11.410223   7.796921 ]]
