<a href="https://colab.research.google.com/github/muyangren907/Machine_Learning/blob/master/TensorFlow%E5%AD%A6%E4%B9%A0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 第一个TensorFlow程序（Hello World）

In [0]:
import tensorflow as tf
message = tf.constant("Hello World")
with tf.Session() as sess:
  print(sess.run(message).decode())

Hello World


# TensorFlow程序结构

In [0]:
v_1 = tf.constant([1,2,3,4])
v_2 = tf.constant([2,1,5,3])
v_add = tf.add(v_1,v_2) # You can also write v_1 + v_2

with tf.Session() as sess:
  print(sess.run(v_add))

# You can also write
# sess = tf.Session()
# print(sess.run(v_add))
# sess.close()

[3 3 8 7]


如果你正在使用 Jupyter Notebook 或者 Python shell 进行编程，使用 tf.InteractiveSession 将比 tf.Session 更方便。InteractiveSession 使自己成为默认会话，因此你可以使用 eval() 直接调用运行张量对象而不用显式调用会话。下面给出一个例子：

In [0]:
sess = tf.InteractiveSession()
v_1 = tf.constant([1,2,3,4])
v_2 = tf.constant([2,1,5,3])
v_add = tf.add(v_1,v_2)
print(v_add.eval())
sess.close()

[3 3 8 7]


/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py:1750: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


# TensorFlow常量、变量和占位符

## TensorFlow 常量

In [0]:
# 声明一个标量常量：
t_1 = tf.constant(4)
with tf.Session() as sess:
  print(sess.run(t_1))

# 一个形如 [1，3] 的常量向量可以用如下代码声明：
t_2 = tf.constant([4,3,2])
with tf.Session() as sess:
  print('\n',sess.run(t_2))

# 要创建一个所有元素为零的张量，可以使用 tf.zeros() 函数。这个语句可以创建
# 一个形如 [M，N] 的零元素矩阵，数据类型（dtype）可以是 int32、float32 等：
# tf.zeros([M,N],tf.dtype)
zero_t = tf.zeros([4,3],tf.int32)
with tf.Session() as sess:
  print('\n',sess.run(zero_t))

# 还可以创建与现有 Numpy 数组或张量常量具有相同形状的张量常量，如下所示：
ones_t = tf.ones_like(zero_t)
with tf.Session() as sess:
  print('\n',sess.run(ones_t))

# 在一定范围内生成一个从初值到终值等差排布的序列：
# tf.linspace(start,stop,num)
# start stop :  fliat
range_t = tf.linspace(1.0,10.0,10)
with tf.Session() as sess:
  print('\n',sess.run(range_t))

# 从开始（默认值=0）生成一个数字序列，增量为 delta（默认值=1），
# 直到终值（但不包括终值）：
# tf.range(start,limit,delta)
range_t = tf.range(1.0,90.0,10)
with tf.Session() as sess:
  print('\n',sess.run(range_t))

# 使用以下语句创建一个具有一定均值（默认值=0.0）和标准差（默认值=1.0）、
# 形状为 [M，N] 的正态分布随机数组：
t_random = tf.random_normal([2,3],2.0,stddev=4,seed=12)
with tf.Session() as sess:
  print('\n',sess.run(t_random))

# 创建一个具有一定均值（默认值=0.0）和标准差（默认值=1.0）、形状为 [M，N] 的
# 截尾正态分布随机数组：
t_random = tf.truncated_normal([1,5],stddev=2,seed=12)
with tf.Session() as sess:
  print('\n',sess.run(t_random))

# 要在种子的 [minval（default=0），maxval] 范围内创建形状为 [M，N] 的给定
# 伽马分布随机数组，请执行如下语句
t_random2 = tf.random_uniform([5,6],maxval=4,seed=12)
with tf.Session() as sess:
  print('\n',sess.run(t_random2))

# 要将给定的张量随机裁剪为指定的大小，使用以下语句：
# t_random 是一个已经定义好的张量。这将导致随机从张量 t_random 中裁剪出一个
# 大小为 [2，5] 的张量。
tf_random_crop = tf.random_crop(t_random2,[4,3],seed=12)
with tf.Session() as sess:
  print('\n',sess.run(tf_random_crop))

# 很多时候需要以随机的顺序来呈现训练样本，可以使用 tf.random_shuffle() 来沿着
# 它的第一维随机排列张量。如果 t_random 是想要重新排序的张量，使用下面的代码：

t_random_shuffle = tf.random_shuffle(tf_random_crop)
with tf.Session() as sess:
  print('\n',sess.run(t_random_shuffle))

# 随机生成的张量受初始种子值的影响。要在多次运行或会话中获得相同的随机数，应该
# 将种子设置为一个常数值。当使用大量的随机张量时，可以使用 tf.set_random_seed() 
# 来为所有随机产生的张量设置种子。以下命令将所有会话的随机张量的种子设置为 54：
tf.set_random_seed(54)

4

 [4 3 2]

 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]

 [[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]

 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

 [ 1. 11. 21. 31. 41. 51. 61. 71. 81.]

 [[-5.3299294  6.88009    6.4126735]
 [ 8.594671  -6.604518  10.532751 ]]

 [[-3.6649647  2.440045   2.2063367  3.2973356  0.3111803]]

 [[0.35454178 3.3739414  0.5591998  0.37541723 0.04065514 3.497334  ]
 [1.4685888  2.7888331  1.9283228  0.3767681  2.2410283  2.9267573 ]
 [1.4547715  2.1593485  1.6037321  3.50946    2.061996   1.9372883 ]
 [0.7182331  1.9995828  3.5743747  3.2437034  0.2526312  0.8461442 ]
 [0.4002676  3.8541117  0.3089533  0.34722805 1.4419994  2.4083471 ]]

 [[3.3739414  0.5591998  0.37541723]
 [2.7888331  1.9283228  0.3767681 ]
 [2.1593485  1.6037321  3.50946   ]
 [1.9995828  3.5743747  3.2437034 ]]

 [[2.7888331  1.9283228  0.3767681 ]
 [1.9995828  3.5743747  3.2437034 ]
 [2.1593485  1.6037321  3.50946   ]
 [3.3739414  0.5591998  0.37541723]]


## TensorFlow 变量

In [0]:
# 它们通过使用变量类来创建。变量的定义还包括应该初始化的常量/随机值。
# 下面的代码中创建了两个不同的张量变量 t_a 和 t_b。
# 两者将被初始化为形状为 [20，30] 的随机均匀分布，最小值=0，最大值=10：
rand_t = tf.random_uniform([20,30],0,10,seed=0)
t_a = tf.Variable(rand_t)
t_b = tf.Variable(rand_t)
# 注意：变量通常在神经网络中表示权重和偏置。

# 下面的代码中定义了两个变量的权重和偏置。
# 权重变量使用正态分布随机初始化，均值为 0，标准差为 2，
# 权重大小为 100×100。偏置由 100 个元素组成，每个元素初始化为 0。
# 在这里也使用了可选参数名以给计算图中定义的变量命名：
weights = tf.Variable(tf.random_normal([100,100],stddev=2))
bias = tf.Variable(tf.zeros(100),name='biases')

# 在前面的例子中，都是利用一些常量来初始化变量，也可以指定一个变量来初始化另一个变量。
# 下面的语句将利用前面定义的权重来初始化 weight2：
weights2 = tf.Variable(weights.initialized_value(),name='w2')

# 变量的定义将指定变量如何被初始化，但是必须显式初始化所有的声明变量。
# 在计算图的定义中通过声明初始化操作对象来实现：
initial_op = tf.global_variables_initializer()

# 每个变量也可以在运行图中单独使用 tf.Variable.initializer 来初始化：
bias = tf.Variable(tf.zeros([100,100]))
with tf.Session() as sess:
  sess.run(bias.initializer)

# 保存变量：使用 Saver 类来保存变量，定义一个 Saver 操作对象：
saver = tf.train.Saver() 

## TensorFlow 占位符

In [0]:
# 介绍完常量和变量之后，我们来讲解最重要的元素——占位符，
# 它们用于将数据提供给计算图。可以使用以下方法定义一个占位符：
# tf.placeholder(dtype,shape=None,name=None)
# dtype 定占位符的数据类型，并且必须在声明占位符时指定。
# 在这里，为 x 定义一个占位符并计算 y=2*x，使用 feed_dict 输入一个随机的 4×5 矩阵：
x = tf.placeholder(tf.float32)
y = 2 * x
data = tf.random_uniform([4,5],10)
with tf.Session() as sess:
  x_data = sess.run(data)
  y_ = sess.run(y,feed_dict={x:x_data})
print(x_data)
print(y_)

[[3.1778164 8.709591  7.535771  5.544607  4.6875687]
 [6.2226806 5.981759  7.0217867 4.8371143 5.2493024]
 [3.974957  3.2180357 5.5360594 7.096443  1.7906361]
 [6.8016834 4.996413  8.032926  5.7051115 3.8984604]]
[[ 6.355633  17.419182  15.071542  11.089214   9.375137 ]
 [12.445361  11.963518  14.043573   9.674229  10.498605 ]
 [ 7.949914   6.4360714 11.072119  14.192886   3.5812721]
 [13.603367   9.992826  16.065851  11.410223   7.796921 ]]


## 注意事项

In [0]:
# 很多时候需要大规模的常量张量对象；在这种情况下，为了优化内存，
# 最好将它们声明为一个可训练标志设置为 False 的变量：
t_large = tf.Varible(large_array,trainable = False)

TensorFlow 被设计成与 Numpy 配合运行，因此所有的TensorFlow 数据类型都是基于 Numpy 的。使用tf.convert_to_tensor() 可以将给定的值转换为张量类型，并将其与 TensorFlow 函数和运算符一起使用。该函数接受 Numpy 数组、Python 列表和 Python 标量，并允许与张量对象互操作。

![TensorFlow 支持的常见的数据类型](http://c.biancheng.net/uploads/allimg/190107/2-1Z10G4153M25.gif)

# TensorFlow矩阵基本操作及其实现

In [0]:
# 矩阵运算，例如执行乘法、加法和减法，是任何神经网络中信号传播的重要操作。通常在计算中需要随机矩阵、零矩阵、一矩阵或者单位矩阵。

import tensorflow as tf
sess = tf.InteractiveSession()
I_matrix = tf.eye(5)
print(I_matrix.eval())

X = tf.Variable(tf.eye(6))
X.initializer.run()
print('\n',X.eval())

A = tf.Variable(tf.random_normal([3,6]))
A.initializer.run()
print('\n',A.eval())

product = tf.matmul(A,X)
print('\n',product.eval())

b = tf.Variable(tf.random_uniform([3,6],0,2,dtype=tf.int32))
b.initializer.run()
print(b.eval())
b_new = tf.cast(b,dtype=tf.float32)
# Cast to float32 data type

t_sum = tf.add(product,b_new)
t_sub = product - b_new
print('A * X + b = ',t_sum.eval())
print('A * X - b = ',t_sub.eval())

# 一些其他有用的矩阵操作，如按元素相乘、乘以一个标量、按元素相除、按元素余数相除等，可以执行如下语句：
a = tf.Variable(tf.random_normal([4,5],stddev=2))
b = tf.Variable(tf.random_normal([4,5],stddev=2))

# 元素相乘
A = a * b

# 乘以一个标量
B = tf.scalar_mul(2,A)

# 按元素相除
C = tf.div(a,b)

# 按元素余数相除
D = tf.mod(a,b)

init_op = tf.global_variables_initializer()
with tf.Session() as sess:
  sess.run(init_op)
  _a,_b,_A,_B,_C,_D = sess.run([a,b,A,B,C,D])

print(_a)
print(_b)
print(_A)
print(_B)
print(_C)
print(_D)

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py:1750: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

 [[-0.01338118 -1.1967833   0.9200098   1.2324066  -0.23509818 -0.23711362]
 [-1.7499586  -1.3421029   1.3887165   1.1838319  -1.3706229  -0.58759654]
 [ 0.92627     0.16264272 -1.8010796   1.8260559  -1.1232027   1.1859559 ]]

 [[-0.01338118 -1.1967833   0.9200098   1.2324066  -0.23509818 -0.23711362]
 [-1.7499586  -1.3421029   1.3887165   1.1838319  -1.3706229  -0.58759654]
 [ 0.92627     0.16264272 -1.8010796   1.8260559  -1.1232027   1.1859559 ]]
[[0 0 1 1 0 0]
 [1 0 0 0 1 1]
 [1 0 1 0 1 1]]
A * X + b =  [[-0.01338118 -1.1967833   1.9200099   2.2324066  -0.23509818 -0.23711362]
 [-0.74995863 -1.3421029   1.3887165   1.1838319  -0.37062287  0.41240346]
 [ 1.92627     0.16264272 -0.80107963  1.8260559  -0.12320268  2.185956  ]]
A * X - b =  [[-0.01338118 -1.1967833  

## 注意事项

所有加法、减、除、乘（按元素相乘）、取余等矩阵的算术运算都要求两个张量矩阵是相同的数据类型，否则就会产生错误。可以使用 tf.cast() 将张量从一种数据类型转换为另一种数据类型。


如果在整数张量之间进行除法，最好使用 tf.truediv(a，b)，因为它首先将整数张量转换为浮点类，然后再执行按位相除。

# TensorFlow TensorBoard可视化数据流图

TensorFlow 使用 TensorBoard 来提供计算图形的图形图像。这使得理解、调试和优化复杂的神经网络程序变得很方便。TensorBoard 也可以提供有关网络执行的量化指标。它读取 TensorFlow 事件文件，其中包含运行 TensorFlow 会话期间生成的摘要数据。

使用 TensorBoard 的第一步是确定想要的 OP 摘要。以 DNN 为例，通常需要知道损失项（目标函数）如何随时间变化。在自适应学习率的优化中，学习率本身会随时间变化。可以在 tf.summary.scalar OP 的帮助下得到需要的术语摘要。假设损失变量定义了误差项，我们想知道它是如何随时间变化的：

In [0]:
loss = tf...
tf.summary.scalar('loss',loss)


还可以使用 tf.summary.histogram 可视化梯度、权重或特定层的输出分布：

In [0]:
output_tensor = tf.matmul(input_tensor,weights) + biases
tf.summary.histogram('output',output_tensor)

摘要将在会话操作中生成。可以在计算图中定义 tf.merge_all_summaries OP 来通过一步操作得到摘要，而不需要单独执行每个摘要操作。

生成的摘要需要用事件文件写入：

In [0]:
writer = tf.summary.FileWriter('summary_dir',sess.graph)

这会将所有摘要和图形写入 summary_dir 目录中。现在，为了可视化摘要，需要从命令行中调用 TensorBoard：

In [0]:
tensorboard --logdir=summary_dir

接下来，打开浏览器并输入地址 http://localhost:6006/（或运行 TensorBoard 命令后收到的链接）。

## Colab中使用TensorBoard

In [0]:
!pip install tensorboardcolab
from tensorboardcolab import TensorBoardColab
tbc = TensorBoardColab()

Wait for 8 seconds...
TensorBoard link:
https://9c244702.ngrok.io


In [0]:
!pip install -q tf-nightly-2.0-preview
from tensorflow import summary
%load_ext tensorboard
%tensorboard --logdir logs/tensorboard

ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
Traceback (most recent call last):
  File "/usr/local/bin/tensorboard", line 8, in <module>
    sys.exit(run_main())
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/main.py", line 59, in run_main
    default.get_plugins() + default.get_dynamic_plugins(),
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/default.py", line 115, in get_dynamic_plugins
    for entry_point in pkg_resources.iter_entry_points('tensorboard_plugins')
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/default.py", line 115, in <listcomp>
    for entry_point in pkg_resources.iter_entry_points('tensorboard_plugins')
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2442, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2465, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  Fil

In [0]:


current_time = str(datetime.datetime.now().timestamp())
train_log_dir = 'logs/tensorboard/train/' + current_time
test_log_dir = 'logs/tensorboard/test/' + current_time
train_summary_writer = summary.create_file_writer(train_log_dir)
test_summary_writer = summary.create_file_writer(test_log_dir)

     |████████████████████████████████| 95.2MB 113kB/s 
     |████████████████████████████████| 3.8MB 52.1MB/s 
     |████████████████████████████████| 450kB 63.0MB/s 
     |████████████████████████████████| 81kB 12.5MB/s 
ERROR: google-colab 1.0.0 has requirement google-auth~=1.4.0, but you'll have google-auth 1.10.0 which is incompatible.
ERROR: tb-nightly 2.1.0a20191206 has requirement grpcio>=1.24.3, but you'll have grpcio 1.15.0 which is incompatible.


RuntimeError: ignored

In [0]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
 
# 载入数据集
mnist = input_data.read_data_sets("MNIST_data", one_hot=True)
 
# 批次的大小
batch_size = 50
 
# 计算一共有多少批次
n_batch = mnist.train.num_examples // batch_size
 
# 输入命名空间
with tf.name_scope("input"):
    # 定义两个placeholder
    x = tf.placeholder(tf.float32, [None, 28 * 28])
    y = tf.placeholder(tf.float32, [None, 10])
 
with tf.name_scope("layer"):
    # 创建一个简单的神经网络
    with tf.name_scope("weight"):
        W = tf.Variable(tf.zeros([784, 10]))
    with tf.name_scope("biases"):
        b = tf.Variable(tf.zeros([10]))
    with tf.name_scope("wx_plus_b"):
        wx_plus_b = tf.matmul(x, W) + b
    with tf.name_scope("softmax"):
        prediction = tf.nn.softmax(wx_plus_b)
 
with tf.name_scope("loss"):
    # 二次代价函数
    loss = tf.reduce_mean(tf.square(y - prediction))
 
with tf.name_scope("train"):
    # 使用梯度下降法
    train_step = tf.train.GradientDescentOptimizer(0.2).minimize(loss)
 
 
# 初始化变量
init = tf.global_variables_initializer()
 
with tf.name_scope("accuracy"):
    with tf.name_scope("correct_prediction"):
        # 计算正确率,下面是一个布尔型列表
        correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(prediction, 1))
    with tf.name_scope("accuracy"):
        # 求准确率，首先把布尔类型转化为浮点类型
        accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
 
with tf.Session() as sess:
    sess.run(init)
    # 保存Tensorboard文件
    writer = tf.summary.FileWriter("logs/", sess.graph)
    for epoch in range(200):
        
        for batch in range(n_batch):
            # 使用函数获取一个批次图片
            batch_xs, batch_ys = mnist.train.next_batch(batch_size)
            sess.run(train_step, feed_dict={x: batch_xs, y: batch_ys})
            
 
        acc = sess.run(accuracy, feed_dict={x: mnist.test.images, y: mnist.test.labels})

        print("Iter " + str(epoch) + ",Testing Accuracy " + str(acc))
        tbc.save_value("just a test", "line_name", epoch,acc)